version: "3.7"

services:

  namenode:
    image: timveil/docker-hadoop-namenode:3.2.x
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hive-3.1.x
    env_file:
      - core.env
      - yarn-remote.env
    ports:
      - "9870:9870"

  datanode:
    image: timveil/docker-hadoop-datanode:3.2.x
    container_name: datanode
    hostname: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - core.env
      - yarn-remote.env
    ports:
      - "9864:9864"

  resourcemanager:
    image: timveil/docker-hadoop-resourcemanager:3.2.x
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
    env_file:
      - core.env
      - yarn-resource-manager.env
    ports:
      - "8088:8088"

  nodemanager:
    image: timveil/docker-hadoop-nodemanager:3.2.x
    container_name: nodemanager
    hostname: nodemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    env_file:
      - core.env
      - yarn-node-manager.env
    ports:
      - "8042:8042"

  historyserver:
    image: timveil/docker-hadoop-historyserver:3.2.x
    container_name: historyserver
    hostname: historyserver
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    env_file:
      - core.env
      - yarn-timeline.env
    ports:
      - "8188:8188"

  hs2:
    image: timveil/docker-hadoop-hive-hs2:3.1.x
    container_name: hs2
    hostname: hs2
    environment:
      - SERVICE_PRECONDITION=metastore:9083
    env_file:
      - core.env
      - yarn-remote.env
      - hive.env
    ports:
      - "10000:10000"
      - "10002:10002"

  metastore:
    image: timveil/docker-hadoop-hive-metastore:3.1.x
    container_name: metastore
    hostname: metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 metastore-db:5432
    env_file:
      - core.env
      - yarn-remote.env
      - hive.env
      - metastore.env

  metastore-db:
    image: timveil/docker-hadoop-hive-metastore-db:3.1.x
    container_name: metastore-db
    hostname: metastore-db